In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("cars.xlsx")

In [3]:
df

       Make     Model  Year    Gear  Engine condition     Price
0    Toyota     Camry  2018  manual     2.0        ok   9000000
1    Toyota     Camry  2020    auto     2.0        ok  13000000
2    Toyota        LC  2015  manual     4.0        ok  12000000
3    Toyota        LC  2000    auto     4.5        ok   7000000
4  Mercedes      E320  2026    auto     3.2        ok  30000000
5       BMW       750  2018  manual     5.0    broken   2500000
6       BMW       325  2025  manual     2.5        ok  35000000
7    Subaru  Forester  2020    auto     2.0        ok  12000000
8     Volvo       850  1985  manual     1.8        ok   3000000

In [4]:
df.head()

       Make  Model  Year    Gear  Engine condition     Price
0    Toyota  Camry  2018  manual     2.0        ok   9000000
1    Toyota  Camry  2020    auto     2.0        ok  13000000
2    Toyota     LC  2015  manual     4.0        ok  12000000
3    Toyota     LC  2000    auto     4.5        ok   7000000
4  Mercedes   E320  2026    auto     3.2        ok  30000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Make       9 non-null      object
 1   Model      9 non-null      object
 2   Year       9 non-null      int64
 3   Gear       9 non-null      object
 4   Engine     9 non-null      float64
 5   condition  9 non-null      object
 6   Price      9 non-null      int64
dtypes: float64(1), int64(2), object(4)
memory usage: 632.0+ bytes

In [8]:
df["is_toyota"] = df["Make"] == "Toyota"
df["is_mercedes"] = df["Make"] == "Mercedes"

In [9]:
df

,Make,Model,Year,Gear,Engine,condition,Price,is_toyota,is_mercedes
0,Toyota,Camry,2018,manual,2.0,ok,9000000,True,False
1,Toyota,Camry,2020,auto,2.0,ok,13000000,True,False
2,Toyota,LC,2015,manual,4.0,ok,12000000,True,False
3,Toyota,LC,2000,auto,4.5,ok,7000000,True,False
4,Mercedes,E320,2026,auto,3.2,ok,30000000,False,True
5,BMW,750,2018,manual,5.0,broken,2500000,False,False
6,BMW,325,2025,manual,2.5,ok,35000000,False,False
7,Subaru,Forester,2020,auto,2.0,ok,12000000,False,False
8,Volvo,850,1985,manual,1.8,ok,3000000,False,False

In [12]:
for make in df["Make"].unique():
    df[make] = df["Make"] == make

In [24]:
df.drop("is_mercedes", axis=1, inplace=True)
# df = df.drop("is_toyota", axis=1)

In [25]:
df

,Make,Model,Year,Gear,Engine,condition,Price,Toyota,Mercedes,BMW,Subaru,Volvo
0,Toyota,Camry,2018,manual,2.0,ok,9000000,True,False,False,False,False
1,Toyota,Camry,2020,auto,2.0,ok,13000000,True,False,False,False,False
2,Toyota,LC,2015,manual,4.0,ok,12000000,True,False,False,False,False
3,Toyota,LC,2000,auto,4.5,ok,7000000,True,False,False,False,False
4,Mercedes,E320,2026,auto,3.2,ok,30000000,False,True,False,False,False
5,BMW,750,2018,manual,5.0,broken,2500000,False,False,True,False,False
6,BMW,325,2025,manual,2.5,ok,35000000,False,False,True,False,False
7,Subaru,Forester,2020,auto,2.0,ok,12000000,False,False,False,True,False
8,Volvo,850,1985,manual,1.8,ok,3000000,False,False,False,False,True

In [29]:
for make in df["Make"].unique():
    df.drop(make, axis=1, inplace=True)

In [33]:
df = pd.get_dummies(df, columns=["Make"])

KeyError: "None of [Index(['Make'], dtype='object')] are in the [columns]"

In [34]:
df = pd.get_dummies(df, columns=["condition"])

In [40]:
df = pd.get_dummies(df, columns=["Gear"])

In [41]:
df

,Model,Year,Engine,Price,Make_BMW,Make_Mercedes,Make_Subaru,Make_Toyota,Make_Volvo,condition_broken,condition_ok,Gear_auto,Gear_manual
0,Camry,2018,2.0,9000000,False,False,False,True,False,False,True,False,True
1,Camry,2020,2.0,13000000,False,False,False,True,False,False,True,True,False
2,LC,2015,4.0,12000000,False,False,False,True,False,False,True,False,True
3,LC,2000,4.5,7000000,False,False,False,True,False,False,True,True,False
4,E320,2026,3.2,30000000,False,True,False,False,False,False,True,True,False
5,750,2018,5.0,2500000,True,False,False,False,False,True,False,False,True
6,325,2025,2.5,35000000,True,False,False,False,False,False,True,False,True
7,Forester,2020,2.0,12000000,False,False,True,False,False,False,True,True,False
8,850,1985,1.8,3000000,False,False,False,False,True,False,True,False,True

In [36]:
from sklearn.linear_model import LinearRegression

In [37]:
model = LinearRegression()

In [39]:
type(model)

sklearn.linear_model._base.LinearRegression

In [47]:
X = df.drop(["Price", "Model"], axis=1)
y = df["Price"]

In [48]:
X

,Year,Engine,Make_BMW,Make_Mercedes,Make_Subaru,Make_Toyota,Make_Volvo,condition_broken,condition_ok,Gear_auto,Gear_manual
0,2018,2.0,False,False,False,True,False,False,True,False,True
1,2020,2.0,False,False,False,True,False,False,True,True,False
2,2015,4.0,False,False,False,True,False,False,True,False,True
3,2000,4.5,False,False,False,True,False,False,True,True,False
4,2026,3.2,False,True,False,False,False,False,True,True,False
5,2018,5.0,True,False,False,False,False,True,False,False,True
6,2025,2.5,True,False,False,False,False,False,True,False,True
7,2020,2.0,False,False,True,False,False,False,True,True,False
8,1985,1.8,False,False,False,False,True,False,True,False,True

In [49]:
y

0     9000000
1    13000000
2    12000000
3     7000000
4    30000000
5     2500000
6    35000000
7    12000000
8     3000000
Name: Price, dtype: int64

In [51]:
model.fit(X,y)

LinearRegression()

In [52]:
model.coef_

array([   600000.        ,   2399999.99999999,  11720000.00000001,
         1640000.00000001,  -9879999.99999998,  -8879999.99999999,
         5399999.99999996, -17149999.99999999,  17149999.99999998,
         1400000.        ,  -1400000.        ])

In [53]:
model.intercept_

-1213469999.999992

In [54]:
df["guess"] = model.predict(X)

In [55]:
df

,Model,Year,Engine,Price,Make_BMW,Make_Mercedes,Make_Subaru,Make_Toyota,Make_Volvo,condition_broken,condition_ok,Gear_auto,Gear_manual,guess
0,Camry,2018,2.0,9000000,False,False,False,True,False,False,True,False,True,9000000.0
1,Camry,2020,2.0,13000000,False,False,False,True,False,False,True,True,False,13000000.0
2,LC,2015,4.0,12000000,False,False,False,True,False,False,True,False,True,12000000.0
3,LC,2000,4.5,7000000,False,False,False,True,False,False,True,True,False,7000000.0
4,E320,2026,3.2,30000000,False,True,False,False,False,False,True,True,False,30000000.0
5,750,2018,5.0,2500000,True,False,False,False,False,True,False,False,True,2500000.0
6,325,2025,2.5,35000000,True,False,False,False,False,False,True,False,True,35000000.0
7,Forester,2020,2.0,12000000,False,False,True,False,False,False,True,True,False,12000000.0
8,850,1985,1.8,3000000,False,False,False,False,True,False,True,False,True,3000000.0

In [56]:
df = pd.DataFrame({
    "father": [170, 180, 175, 165, 160, 175],
    "mother": [160, 175, 180, 170, 160, 190],
    "child":  [173, 190, 191, 175, 165, 193],
})

In [57]:
df

   father  mother  child
0     170     160    173
1     180     175    190
2     175     180    191
3     165     170    175
4     160     160    165
5     175     190    193

In [67]:
X = df[["father", "mother"]]
y = df["child"]

In [69]:
model = LinearRegression()
model.fit(X,y)

LinearRegression()

In [71]:
df["ml"] = model.predict(X)

In [72]:
df

   father  mother  child          ml
0     170     160    173  173.607646
1     180     175    190  190.378270
2     175     180    191  188.839034
3     165     170    175  174.806841
4     160     160    165  165.052314
5     175     190    193  194.315895

In [74]:
model.coef_

array([0.8555332 , 0.54768612])

In [75]:
model.intercept_

-59.462776659959786

In [76]:
180*0.855 + 175*0.5476 - 59.46277

190.26723

In [77]:
df_test = pd.DataFrame({
    "father": [180, 190, 205, 175, 175, 170],
    "mother": [170, 178, 180, 180, 190, 190],
})

In [79]:
childred = model.predict(df_test)

In [80]:
df_test["child"] = childred

In [81]:
df_test

   father  mother       child
0     180     170  187.639839
1     190     178  200.576660
2     205     180  214.505030
3     175     180  188.839034
4     175     190  194.315895
5     170     190  190.038229