In [ ]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_excel("Book1.xlsx")

In [4]:
df

       Make     Model  Year     Price
0    Toyota     Camry  2018   9000000
1    Toyota     Camry  2020  13000000
2    Toyota        LC  2015  12000000
3    Toyota        LC  2000   7000000
4  Mercedes      E320  2026  30000000
5       BMW       750  2018   5000000
6       BMW       325  2025  35000000
7    Subaru  Forester  2020  12000000
8     Volvo       850  1985  25000000

In [13]:
df["Good deal"] = (df["Price"] <= 10000000) & (df["Year"] >= 2015)

In [14]:
df

       Make     Model  Year     Price  Good deal
0    Toyota     Camry  2018   9000000       True
1    Toyota     Camry  2020  13000000      False
2    Toyota        LC  2015  12000000      False
3    Toyota        LC  2000   7000000      False
4  Mercedes      E320  2026  30000000      False
5       BMW       750  2018   5000000       True
6       BMW       325  2025  35000000      False
7    Subaru  Forester  2020  12000000      False
8     Volvo       850  1985  25000000      False

In [15]:
# группируем по марке и считаем, сколько машин каждой марки
df.groupby("Make").size()

Make
BMW         2
Mercedes    1
Subaru      1
Toyota      4
Volvo       1
dtype: int64

In [16]:
# группируем по марке и берём средню цену
df.groupby("Make")["Price"].mean()

Make
BMW         20000000.0
Mercedes    30000000.0
Subaru      12000000.0
Toyota      10250000.0
Volvo       25000000.0
Name: Price, dtype: float64

In [18]:
# сортируем всю таблицу по цене (по возрастанию)
df.sort_values("Price", ascending=False)

       Make     Model  Year     Price  Good deal
6       BMW       325  2025  35000000      False
4  Mercedes      E320  2026  30000000      False
8     Volvo       850  1985  25000000      False
1    Toyota     Camry  2020  13000000      False
2    Toyota        LC  2015  12000000      False
7    Subaru  Forester  2020  12000000      False
0    Toyota     Camry  2018   9000000       True
3    Toyota        LC  2000   7000000      False
5       BMW       750  2018   5000000       True

In [20]:
df.sort_values(by=["Year", "Price"], ascending=[False, True])

       Make     Model  Year     Price  Good deal
4  Mercedes      E320  2026  30000000      False
6       BMW       325  2025  35000000      False
7    Subaru  Forester  2020  12000000      False
1    Toyota     Camry  2020  13000000      False
5       BMW       750  2018   5000000       True
0    Toyota     Camry  2018   9000000       True
2    Toyota        LC  2015  12000000      False
3    Toyota        LC  2000   7000000      False
8     Volvo       850  1985  25000000      False

## 100 Toyotas - синтетические данные

In [27]:
# создаём 100 синтетических Toyotas
n = 100
models = ["Camry", "Corolla", "RAV4", "LC", "Prado", "Highlander", "Yaris", "Avensis"]
cities = ["Almaty", "Astana", "Shymkent", "Karaganda", "Atyrau", "Actau"]

np.random.seed(42)

# базовая цена по модели
base_price = {
    "Camry": 12_000_000,
    "Corolla": 8_000_000,
    "RAV4": 14_000_000,
    "LC": 25_000_000,
    "Prado": 18_000_000,
    "Highlander": 16_000_000,
    "Yaris": 6_000_000,
    "Avensis": 10_000_000,
}

# генерируем модели и годы
model_list = np.random.choice(models, n)
year_list = np.random.randint(2005, 2026, n)

# цена = базовая цена - (2025 - год) * 500_000 + случайный шум
price_list = []
for model, year in zip(model_list, year_list):
    base = base_price[model]
    depreciation = (2025 - year) * 500_000  # теряет ~500k в год
    noise = np.random.randint(-2_000_000, 3_000_000)  # ±2-3 млн случайно
    price = max(2_000_000, base - depreciation + noise)  # минимум 2 млн
    price_list.append(price)

toyotas = pd.DataFrame({
    "make": ["Toyota"] * n,
    "model": model_list,
    "year": year_list,
    "mileage": np.random.randint(0, 300_000, n),
    "price": price_list,
    "city": np.random.choice(cities, n),
})
toyotas.head(10)

     make    model  year  mileage     price       city
0  Toyota    Yaris  2022   112296   6922880     Atyrau
1  Toyota       LC  2016    94179  21612754  Karaganda
2  Toyota    Prado  2006    90272   7884250  Karaganda
3  Toyota    Yaris  2014    38467   2525717  Karaganda
4  Toyota     RAV4  2008   285472   3561087     Atyrau
5  Toyota  Avensis  2018   135059   5996176  Karaganda
6  Toyota    Prado  2020    58871  15386013      Actau
7  Toyota    Prado  2019   128391  17634096     Atyrau
8  Toyota    Yaris  2012    86416   2000000  Karaganda
9  Toyota  Corolla  2018   256687   5860011      Actau

In [31]:
# размер датасета
toyotas.shape

(100, 6)

In [54]:
url = "https://nationalbank.kz/ru/exchangerates/ezhednevnye-oficialnye-rynochnye-kursy-valyut"
tables = pd.read_html(url, flavor="lxml")
a = tables[0]
rate = a[a[2] == "USD / KZT"][3]

In [55]:
300 * rate

10    147411.0
Name: 3, dtype: float64

In [57]:
len(tables)

1

In [60]:
url = "https://nationalbank.kz/ru/exchangerates/ezhednevnye-oficialnye-rynochnye-kursy-valyut/report?_token=tFHNYVWUjUpxSgr5a5G7wr7oN6mzcMOFRR6OoHzq&beginDate=01.05.2026&endDate=16.06.2026&search-exchanges=&rates%5B%5D=5"
tables = pd.read_html(url, flavor="lxml")
usd = tables[0]

In [61]:
usd

    Unnamed: 0  Числовое значение  ДОЛЛАР США
0   2026-05-01                  1      462.91
1   2026-05-02                  1      462.91
2   2026-05-03                  1      462.91
3   2026-05-04                  1      462.91
4   2026-05-05                  1      464.53
5   2026-05-06                  1      465.01
6   2026-05-07                  1      463.41
7   2026-05-08                  1      463.41
8   2026-05-09                  1      461.26
9   2026-05-10                  1      461.26
10  2026-05-11                  1      461.26
11  2026-05-12                  1      461.26
12  2026-05-13                  1      463.91
13  2026-05-14                  1      467.63
14  2026-05-15                  1      474.04
15  2026-05-16                  1      470.17
16  2026-05-17                  1      470.17
17  2026-05-18                  1      470.17
18  2026-05-19                  1      467.58
19  2026-05-20                  1      471.93
20  2026-05-21                  1      471.77
21  2026-05-22                  1      471.45
22  2026-05-23                  1      470.80
23  2026-05-24                  1      470.80
24  2026-05-25                  1      470.80
25  2026-05-26                  1      472.48
26  2026-05-27                  1      477.48
27  2026-05-28                  1      477.48
28  2026-05-29                  1      485.55
29  2026-05-30                  1      485.95
30  2026-05-31                  1      485.95
31  2026-06-01                  1      485.95
32  2026-06-02                  1      488.96
33  2026-06-03                  1      493.15
34  2026-06-04                  1      489.31
35  2026-06-05                  1      485.34
36  2026-06-06                  1      487.44
37  2026-06-07                  1      487.44
38  2026-06-08                  1      487.44
39  2026-06-09                  1      484.78
40  2026-06-10                  1      490.21
41  2026-06-11                  1      488.59
42  2026-06-12                  1      487.76
43  2026-06-13                  1      489.33
44  2026-06-14                  1      489.33
45  2026-06-15                  1      489.33
46  2026-06-16                  1      491.37

In [62]:
usd.sort_values("ДОЛЛАР США")

    Unnamed: 0  Числовое значение  ДОЛЛАР США
9   2026-05-10                  1      461.26
11  2026-05-12                  1      461.26
10  2026-05-11                  1      461.26
8   2026-05-09                  1      461.26
0   2026-05-01                  1      462.91
3   2026-05-04                  1      462.91
2   2026-05-03                  1      462.91
1   2026-05-02                  1      462.91
6   2026-05-07                  1      463.41
7   2026-05-08                  1      463.41
12  2026-05-13                  1      463.91
4   2026-05-05                  1      464.53
5   2026-05-06                  1      465.01
18  2026-05-19                  1      467.58
13  2026-05-14                  1      467.63
15  2026-05-16                  1      470.17
16  2026-05-17                  1      470.17
17  2026-05-18                  1      470.17
24  2026-05-25                  1      470.80
22  2026-05-23                  1      470.80
23  2026-05-24                  1      470.80
21  2026-05-22                  1      471.45
20  2026-05-21                  1      471.77
19  2026-05-20                  1      471.93
25  2026-05-26                  1      472.48
14  2026-05-15                  1      474.04
26  2026-05-27                  1      477.48
27  2026-05-28                  1      477.48
39  2026-06-09                  1      484.78
35  2026-06-05                  1      485.34
28  2026-05-29                  1      485.55
29  2026-05-30                  1      485.95
30  2026-05-31                  1      485.95
31  2026-06-01                  1      485.95
37  2026-06-07                  1      487.44
36  2026-06-06                  1      487.44
38  2026-06-08                  1      487.44
42  2026-06-12                  1      487.76
41  2026-06-11                  1      488.59
32  2026-06-02                  1      488.96
34  2026-06-04                  1      489.31
43  2026-06-13                  1      489.33
45  2026-06-15                  1      489.33
44  2026-06-14                  1      489.33
40  2026-06-10                  1      490.21
46  2026-06-16                  1      491.37
33  2026-06-03                  1      493.15